runtime: nodejs
env: flex

manual_scaling:
  instances: 1

network:
  session_affinity: true

env_variables:
  ORIGINS: "web-rtc-bvgk656t5.now.sh,web-rtc.jptomanelli.now.sh,web-rtc-sigma.now.sh,web-rtc-git-master.jptomanelli.now.sh"